# Generated by Django 6.0.2 on 2026-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmodule", "0003_author_publisher_remove_book_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="course_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Student2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("addresses", models.ManyToManyField(to="bookmodule.address2")),
            ],
        ),
    ]
